#!/usr/bin/env python3
"""Builds data/macs.json: every Intel Mac (2008-2020) with its Apple model
number (A-number), identifier and Second Wind support level + plain notes.

Source table (data/mac-models-source.json): names/identifiers/T2 from Apple's
"Identify your Mac model" pages; A-numbers from everymac (Apple no longer lists
them). Support levels come from the driver research (23-09-2026) and MUST be
updated as real installs are reported. Levels:
  verified     installed end-to-end on real hardware by us
  expected     every component has a driver on the stick; not yet tested by us
  partial      works, with one named limitation
  beta         real unknowns; try only if you accept rough edges
  unsupported  do not install (the stick also refuses these before wiping)
"""
import json, os, re
here = os.path.dirname(os.path.abspath(__file__))
src = json.load(open(os.path.join(here, "mac-models-source.json")))

NOTES = {
  "t2": ("Tiene chip T2 (2018-2020): todavía no es compatible. El pendrive se detiene sin borrar nada.",
         "Has the T2 chip (2018-2020): not supported yet. The stick stops without erasing anything."),
  "old": ("Mac antiguo: necesita 4 GB de memoria o más y puede ir lento.",
          "Older Mac: needs 4 GB of memory or more and may feel slow."),
  "nowifi": ("Su WiFi no tiene driver en Linux. No recomendado.",
             "Its WiFi has no Linux driver. Not recommended."),
  "4331": ("WiFi incluido en el pendrive desde la versión 0.9.3; aún sin prueba en este modelo.",
           "WiFi included on the stick since version 0.9.3; not yet tested on this model."),
  "ok": ("Todo tiene driver en el pendrive. La cámara (si tiene) se activa sola al conectarte al WiFi.",
         "Everything has a driver on the stick. The camera (if any) turns on by itself once you join WiFi."),
  "5ghz": ("Funciona. El WiFi en 5 GHz puede tener señal débil (2,4 GHz va bien).",
           "Works. WiFi on 5 GHz may have a weak signal (2.4 GHz is fine)."),
  "audio": ("Funciona, pero el sonido de los parlantes aún no (lo estamos resolviendo).",
            "Works, but the built-in speakers don't play sound yet (we're working on it)."),
  "touchbar": ("Beta: la Touch Bar (y con ella Esc y las teclas F), el sonido y el WiFi tienen limitaciones.",
               "Beta: the Touch Bar (and with it Esc and the F keys), sound and WiFi have limitations."),
  "macbook12": ("Beta: aún no confirmamos el WiFi ni el reposo en este modelo.",
                "Beta: WiFi and sleep are not confirmed on this model yet."),
  "macpro_old": ("Beta: depende de la tarjeta gráfica instalada.",
                 "Beta: depends on the installed graphics card."),
  "imac2019": ("Beta: su WiFi puede necesitar archivos de macOS. Aún sin confirmar.",
               "Beta: its WiFi may need files from macOS. Not confirmed yet."),
}

def classify(ids, year, t2):
    i = ids[0]
    fam, maj = re.match(r"([A-Za-z]+)(\d+),", i).groups(); maj = int(maj)
    if t2: return "unsupported", "t2"
    if fam == "MacBookAir" and maj <= 2: return "unsupported", "nowifi"
    if fam == "iMac" and maj == 19: return "beta", "imac2019"
    if fam == "MacBook" and maj >= 8: return "beta", "macbook12"
    if fam == "MacBookPro" and any(x in ids for x in ("MacBookPro13,2","MacBookPro13,3","MacBookPro14,2","MacBookPro14,3")):
        return "beta", "touchbar"
    if fam == "MacBookPro" and maj in (13, 14): return "partial", "audio"
    if fam == "iMac" and maj == 18: return "partial", "audio"
    if any(x in ids for x in ("MacBookPro11,4","MacBookPro11,5","MacBookPro12,1","iMac17,1")): return "partial", "5ghz"
    if fam == "MacPro" and maj <= 5: return "beta", "macpro_old"
    if year <= 2010: return "beta", "old"
    # 2011-2012 BCM4331 machines (MacBook Air 2011-12 use BCM43224, in the stock kernel)
    if (fam == "MacBookPro" and maj in (8, 9, 10)) or (fam == "iMac" and maj in (12, 13)) or (fam == "Macmini" and maj in (5, 6)):
        return "expected", "4331"
    return "expected", "ok"

out = []
for m in src["models"]:
    tier, key = classify(m["identifiers"], m["year"], m["t2"])
    out.append({"name": m["name"], "family": m["family"], "year": m["year"],
                "identifiers": m["identifiers"], "a_numbers": m["a_numbers"],
                "support": tier, "note_es": NOTES[key][0], "note_en": NOTES[key][1]})
out.sort(key=lambda r: (r["family"], r["year"], r["name"]))
json.dump({"_about": "Generated by data/build-macs.py. Do not edit by hand.",
           "levels": ["verified", "expected", "partial", "beta", "unsupported"],
           "models": out,
           "ambiguous_a_numbers": src["ambiguous_a_numbers"],
           "apple_silicon_a_numbers": src["apple_silicon_a_numbers"]},
          open(os.path.join(here, "macs.json"), "w"), ensure_ascii=False, indent=1)
from collections import Counter
print(Counter(r["support"] for r in out))

# --- Human tables (EN + ES) generated from the same data --------------------
LBL = {"es": {"verified": "✅ Probado", "expected": "🟢 Debería funcionar", "partial": "🟡 Funciona con un límite",
              "beta": "🟠 Beta", "unsupported": "⛔ No compatible aún",
              "h": "| Modelo | Año | Número de modelo (tapa de abajo) | Identificador | Estado | Nota |",
              "title": "# ¿Sirve mi Mac?\n\nBusca tu Mac por su **número de modelo** (impreso en la tapa de abajo, por ejemplo A1466) **y su año** (Menú Apple > Acerca de este Mac). Ojo: un mismo número de modelo se repite entre años (A1466 = MacBook Air 13\" de 2012 a 2017), por eso importa el año.\n"},
       "en": {"verified": "✅ Tested", "expected": "🟢 Should work", "partial": "🟡 Works, one limit",
              "beta": "🟠 Beta", "unsupported": "⛔ Not supported yet",
              "h": "| Model | Year | Model number (bottom case) | Identifier | Status | Note |",
              "title": "# Will my Mac work?\n\nFind your Mac by its **model number** (printed on the bottom case, e.g. A1466) **and its year** (Apple menu > About This Mac). Note: the same model number repeats across years (A1466 = 13\" MacBook Air from 2012 to 2017), so the year matters.\n"}}
for lang, fn in (("es", "compatibilidad-modelos.md"), ("en", "compatibility-models.md")):
    L = LBL[lang]
    lines = [L["title"], "_Generated from data/macs.json._\n"]
    for fam in sorted({r["family"] for r in out}):
        lines += [f"\n## {fam}\n", L["h"], "|---|---|---|---|---|---|"]
        for r in [x for x in out if x["family"] == fam]:
            lines.append(f"| {r['name']} | {r['year']} | {', '.join(r['a_numbers'])} | {', '.join(r['identifiers'])} | {L[r['support']]} | {r['note_'+lang]} |")
    open(os.path.join(here, "..", "docs", fn), "w").write("\n".join(lines) + "\n")

# --- Swift copy for the macOS Creator (compiled in, no bundle resources) ----
compact = [{"n": r["name"], "y": r["year"], "i": r["identifiers"], "a": r["a_numbers"],
            "s": r["support"], "es": r["note_es"], "en": r["note_en"]} for r in out]
js = json.dumps(compact, ensure_ascii=False, separators=(",", ":"))
swift = ("// GENERATED by data/build-macs.py from data/macs.json. Do not edit by hand.\n"
         "// The Mac catalog compiled into the Creator (works offline, no bundle).\n"
         "enum MacCatalogData {\n    static let json = #\"\"\"\n" + js + "\n\"\"\"#\n}\n")
open(os.path.join(here, "..", "creator", "macos", "Sources", "CreatorCore", "MacCatalogData.swift"), "w").write(swift)
